# Generated by Django 5.1.5 on 2025-04-21 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besoindocument',
            name='lien_document',
        ),
        migrations.AddField(
            model_name='besoindocument',
            name='document',
            field=models.FileField(default='http://exemple.com/default.pdf', upload_to='documents_besoins/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'jpg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='besoindocument',
            name='besoin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.besoin'),
        ),
        migrations.AlterField(
            model_name='besoindocument',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
