# Generated by Django 5.1.5 on 2025-06-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_typevehicule_vehicule_entretienvehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='immatricule',
            new_name='immatriculation',
        ),
    ]
