# Generated by Django 5.1.5 on 2025-06-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_immatricule_vehicule_immatriculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretienvehicule',
            old_name='immatricule',
            new_name='vehicule',
        ),
    ]
