# Generated by Django 5.1.5 on 2025-07-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_immatricule_entretienvehicule_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sursalaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_brut_2025', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('age', models.IntegerField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_augmentation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('augmentation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotisation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.simulationsalaire')),
            ],
        ),
    ]
