# Generated by Django 5.1.5 on 2025-07-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_simulationsalaire_simulationhistorique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationHistorique2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('age', models.IntegerField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_augmentation', models.DecimalField(decimal_places=2, max_digits=5)),
                ('augmentation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotisation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique2', to='api.simulationsalaire')),
            ],
        ),
    ]
