# Generated by Django 5.1.5 on 2026-02-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_categoriecomptable_classecomptable_postereporting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptecomptable',
            name='categoriecomptable',
        ),
    ]
