# Generated by Django 5.1.5 on 2026-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_comptecomptable_categoriecomptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besoin',
            name='reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
