# Generated by Django 5.1.5 on 2026-03-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_besoin_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date_menu',
            field=models.DateField(),
        ),
    ]
