# Generated by Django 5.1.5 on 2026-03-10 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_typeequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='typeequipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.typeequipe'),
            preserve_default=False,
        ),
    ]
