# Generated by Django 5.1.5 on 2026-03-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ← CORRIGÉ : pointe vers 0014 qui est la vraie branche principale
        ('api', '0014_menu_typeequipe'),
    ]

    operations = [
        # ── Commande ──────────────────────────────────────────────────
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(
                choices=[
                    ('en_attente', 'En attente'),
                    ('annulee', 'Annulée'),
                    ('retiree', 'Retirée'),
                ],
                default='en_attente',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='menu',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commandes',
                to='api.menu',
            ),
        ),
        migrations.AlterField(
            model_name='commande',
            name='plat',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commandes',
                to='api.plat',
            ),
        ),
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='commandes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name='commande',
            name='est_annule',
        ),
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together={('user', 'menu', 'plat')},
        ),

        # ── Retrait ───────────────────────────────────────────────────
        migrations.AlterModelOptions(
            name='retrait',
            options={'ordering': ['-date_retrait']},
        ),
        migrations.AddField(
            model_name='retrait',
            name='badge_matricule',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrait',
            name='menu',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='retraits',
                to='api.menu',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retrait',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='retraits',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='retrait',
            name='commande',
        ),
        migrations.AlterUniqueTogether(
            name='retrait',
            unique_together={('user', 'menu')},
        ),
    ]
