# Generated by Django 5.1.5 on 2026-03-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_menu_typeequipe'),
        ('api', '0015_alter_commande_options_alter_retrait_options_and_more'),
    ]

    operations = [
    ]
