# Generated by Django 5.1.5 on 2026-04-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_categoriesalarie_fonction_platcategoriesalarie_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencePrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agence')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestataire')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statut')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
