# Generated by Django 5.1.5 on 2026-10-07 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_notification_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platimage",
            name="image",
            field=models.FileField(
                upload_to="images_plats/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
