// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj2ivb1V-nmdioUyD0A-3FgjJ1ULHTjpk',
    appId: '1:518841892567:web:5d40553f0e590daa967a92',
    messagingSenderId: '518841892567',
    projectId: 'ubifood-1605e',
    authDomain: 'ubifood-1605e.firebaseapp.com',
    storageBucket: 'ubifood-1605e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDanvY5hb2kCzFWm32ZUhIPECEyuzO80Tc',
    appId: '1:518841892567:android:ac9e459775f989a4967a92',
    messagingSenderId: '518841892567',
    projectId: 'ubifood-1605e',
    storageBucket: 'ubifood-1605e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52Z3ypECKyZaCrdYqMuMPIdc1476NFew',
    appId: '1:518841892567:ios:e77a3562530d4b5f967a92',
    messagingSenderId: '518841892567',
    projectId: 'ubifood-1605e',
    storageBucket: 'ubifood-1605e.firebasestorage.app',
    iosBundleId: 'com.example.ubifood',
  );
}
